apiVersion: v1
kind: ConfigMap
metadata:
  name: events-config
data:
  PORT: "4055"
  PREFIX: "events"
  ENV: "development"
  PLATFORM_URL: "http://events:4055"
  MONGO_URI: "mongodb://mongodb-primary:27017/events_db?replicaSet=rs0"
  KAFKA_BROKER: "redpanda-headless:9092"
  RAW_TOPIC: "events.events_development.event"
  PROCESSED_API_BASE: "http://localhost:4055/processedevent/api"
