apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: meshobj-examples-events

commonLabels:
  app.kubernetes.io/part-of: meshobj-examples-events

resources:
- namespace.yaml
- mongodb-statefulset.yaml
- mongodb-service.yaml
- mongodb-init-job.yaml
- mongodb-init-collections-configmap.yaml
- mongodb-init-collections-job.yaml
- redpanda-configmap.yaml
- redpanda-statefulset.yaml
- redpanda-service.yaml
- debezium-configmap.yaml
- debezium-deployment.yaml
